/*
 * Copyright (c) 2024 Alif Semiconductor.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/sys/slist.h>
#include <zephyr/arch/arm/mpu/arm_mpu.h>

#define ALIF_HOST_OSPI_REG		0x83000000
#define ALIF_HOST_OSPI_SIZE		KB(16)

#define ALIF_HOST_PERIPHERAL_BASE	0x1A000000
#define ALIF_HOST_PERIPHERAL_SIZE	MB(16)

#define ALIF_HOST_OSPI0_XIP_BASE	0xA0000000
#define ALIF_HOST_OSPI0_XIP_SIZE	MB(512)

#define REGION_OSPI_FLASH_ATTR(base, size) \
{\
	.rbar = RO_Msk | NON_SHAREABLE_Msk, \
	/* Cache-ability */ \
	.mair_idx = MPU_MAIR_INDEX_SRAM_NOCACHE, \
	.r_limit = REGION_LIMIT_ADDR(base, size),  \
}

#define MRAM_BOOT_PARTITION_ADDR	DT_FIXED_PARTITION_ADDR(DT_NODELABEL(boot_partition))
#define MRAM_STORAGE_PARTITION_ADDR	DT_FIXED_PARTITION_ADDR(DT_NODELABEL(storage_partition))
#define MRAM_STORAGE_PARTITION_SIZE	DT_REG_SIZE(DT_NODELABEL(storage_partition))

#define FLASH_MRAM_BASE_ADDR	MRAM_BOOT_PARTITION_ADDR
#define FLASH_MRAM_SIZE		(MRAM_STORAGE_PARTITION_ADDR - MRAM_BOOT_PARTITION_ADDR)

static const struct arm_mpu_region mpu_regions[] = {
	/* Region 0 */
	MPU_REGION_ENTRY("FLASH_MRAM", FLASH_MRAM_BASE_ADDR,
			 REGION_FLASH_ATTR(FLASH_MRAM_BASE_ADDR, FLASH_MRAM_SIZE)),
	/* Region 1 */
	MPU_REGION_ENTRY("ITCM", DT_REG_ADDR(DT_NODELABEL(itcm)),
			 REGION_FLASH_ATTR(DT_REG_ADDR(DT_NODELABEL(itcm)),
							DT_REG_SIZE(DT_NODELABEL(itcm)))),
	/* Region 2 */
	MPU_REGION_ENTRY("DTCM", DT_REG_ADDR(DT_NODELABEL(dtcm)),
			 REGION_RAM_ATTR(DT_REG_ADDR(DT_NODELABEL(dtcm)),
							DT_REG_SIZE(DT_NODELABEL(dtcm)))),
	/* Region 3 */
	MPU_REGION_ENTRY("OSPI_CTRL", ALIF_HOST_OSPI_REG,
			 REGION_DEVICE_ATTR(ALIF_HOST_OSPI_REG, ALIF_HOST_OSPI_SIZE)),
	/* Region 4 */
	MPU_REGION_ENTRY("PERIPHERALS", ALIF_HOST_PERIPHERAL_BASE,
			 REGION_DEVICE_ATTR(ALIF_HOST_PERIPHERAL_BASE,
							ALIF_HOST_PERIPHERAL_SIZE)),
	/* Region 5 */
	MPU_REGION_ENTRY("OSPI0_XIP", ALIF_HOST_OSPI0_XIP_BASE,
			 REGION_OSPI_FLASH_ATTR(ALIF_HOST_OSPI0_XIP_BASE,
							ALIF_HOST_OSPI0_XIP_SIZE)),
	/* Region 6 */
	MPU_REGION_ENTRY("MRAM_STORAGE", MRAM_STORAGE_PARTITION_ADDR,
			REGION_DEVICE_ATTR(MRAM_STORAGE_PARTITION_ADDR,
							MRAM_STORAGE_PARTITION_SIZE)),
};

const struct arm_mpu_config mpu_config = {
	.num_regions = ARRAY_SIZE(mpu_regions),
	.mpu_regions = mpu_regions,
};
