# Copyright 2026 Alif Semiconductor.
# SPDX-License-Identifier: Apache-2.0

# E8 dev kit specific configs
CONFIG_SDHC_INIT_PRIORITY=80

# Optional SD UHS (voltage switching support on E8 DK)
# All Card doesn't support 1.8v
#CONFIG_SD_UHS_PROTOCOL=y

# Regulator (for SD power)
CONFIG_REGULATOR=y
